# Generated by Django 5.0.8 on 2026-03-28 17:59

import bulb.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('location_name', models.CharField(blank=True, default='', max_length=100)),
                ('device_token', models.CharField(default=bulb.models.generate_device_token, editable=False, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=False)),
                ('firmware_version', models.CharField(blank=True, default='', max_length=50)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('is_on', models.BooleanField(default=False)),
                ('brightness', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_bulbs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ControlActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ON', 'Turn ON'), ('OFF', 'Turn OFF'), ('BRIGHTNESS', 'Set Brightness'), ('SCHEDULE_APPLIED', 'Schedule Applied'), ('DEVICE_REPORTED', 'Device Reported')], max_length=32)),
                ('value', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bulb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='bulb.bulb')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulb_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LightSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('target_is_on', models.BooleanField()),
                ('target_brightness', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('repeat', models.BooleanField(default=False)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('time_of_day', models.TimeField(blank=True, null=True)),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('timezone_name', models.CharField(default='UTC', max_length=64)),
                ('bulb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='bulb.bulb')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bulb_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_run_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PowerReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('current_rms', models.FloatField(help_text='Measured current in amps')),
                ('estimated_voltage', models.FloatField(default=120, help_text='Estimated voltage of the mains')),
                ('estimated_power_w', models.FloatField(help_text='Calculated power of the mains')),
                ('cumulative_energy_wh', models.FloatField(default=0.0)),
                ('bulb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='power_readings', to='bulb.bulb')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulbAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('controller', 'Controller'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bulb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='bulb.bulb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulb_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['bulb_id', 'user_id'],
                'unique_together': {('user', 'bulb')},
            },
        ),
    ]
