# Generated by Django 5.0.8 on 2026-03-22 20:32

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ON', 'Turn ON'), ('OFF', 'Turn OFF'), ('BRIGHTNESS', 'Set Brightness')], max_length=16)),
                ('value', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LightSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('target_is_on', models.BooleanField()),
                ('target_brightness', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('repeat', models.BooleanField(default=False)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('time_of_day', models.TimeField(blank=True, null=True)),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('timezone_name', models.CharField(default='UTC', max_length=64)),
            ],
            options={
                'ordering': ['next_run_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LightState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_on', models.BooleanField(default=False)),
                ('brightness', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'permissions': [('can_control_bulb', 'Can control the light bulb')],
            },
        ),
        migrations.CreateModel(
            name='PowerReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('current_rms', models.FloatField(help_text='Measured current in amps')),
                ('estimated_voltage', models.FloatField(default=120, help_text='Estimated voltage of the mains')),
                ('estimated_power_w', models.FloatField(help_text='Calculated power of the mains')),
                ('cumulative_energy_wh', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
