# Generated by Django 5.0.8 on 2026-03-28 18:56

import bulb.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bulb',
            name='claim_code',
            field=models.CharField(db_index=True, default=bulb.models.generate_claim_code, editable=False, max_length=16),
        ),
        migrations.AddField(
            model_name='bulb',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bulb',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_bulbs', to=settings.AUTH_USER_MODEL),
        ),
    ]
