# Generated by Django 5.0.8 on 2026-02-01 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightstate',
            name='brightness',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
