# Generated by Django 5.0.8 on 2026-02-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulb', '0002_lightstate_brightness'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlactivity',
            name='value',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='controlactivity',
            name='action',
            field=models.CharField(choices=[('ON', 'Turn ON'), ('OFF', 'Turn OFF'), ('BRIGHTNESS', 'Set Brightness')], max_length=16),
        ),
    ]
