# Generated by Django 5.0.8 on 2026-03-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulb', '0002_bulb_claim_code_bulb_claimed_at_alter_bulb_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulb',
            name='pairing_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='bulb',
            name='pairing_mode_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
