# Generated by Django 5.0.8 on 2026-04-22 21:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulb', '0003_bulb_pairing_expires_at_bulb_pairing_mode_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='controlactivity',
            name='actor_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='controlactivity',
            name='actor_role',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='controlactivity',
            name='outcome',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('skipped', 'Skipped'), ('reported', 'Reported')], default='accepted', max_length=16),
        ),
        migrations.AddField(
            model_name='controlactivity',
            name='overridden_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='override_children', to='bulb.controlactivity'),
        ),
        migrations.AddField(
            model_name='controlactivity',
            name='overrode_existing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controlactivity',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='controlactivity',
            name='resulting_brightness',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='controlactivity',
            name='resulting_is_on',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlactivity',
            name='source_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_activities', to='bulb.lightschedule'),
        ),
        migrations.AddField(
            model_name='controlactivity',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('schedule', 'Schedule'), ('device', 'Device'), ('system', 'System')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='lightschedule',
            name='created_by_role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('admin', 'Admin'), ('controller', 'Controller'), ('viewer', 'Viewer')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='lightschedule',
            name='created_by_role_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='controlactivity',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ActiveBulbOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('schedule', 'Schedule'), ('device', 'Device'), ('system', 'System')], default='manual', max_length=16)),
                ('actor_role', models.CharField(blank=True, default='', max_length=20)),
                ('actor_priority', models.IntegerField(default=0)),
                ('target_is_on', models.BooleanField(default=False)),
                ('target_brightness', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('active_until', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bulb', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_override', to='bulb.bulb')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bulb_overrides', to=settings.AUTH_USER_MODEL)),
                ('source_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='override_records', to='bulb.controlactivity')),
            ],
            options={
                'ordering': ['-active_until'],
            },
        ),
    ]
