# Generated by Django 5.0.8 on 2026-02-01 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulb', '0003_controlactivity_value_alter_controlactivity_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lightstate',
            options={'permissions': [('can_control_bulb', 'Can control the light bulb')]},
        ),
    ]
