# Generated by Django 5.0.8 on 2026-04-22 23:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulb', '0004_controlactivity_actor_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlactivity',
            name='reason_code',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('permission_denied', 'Denied by permissions'), ('active_higher_priority_control', 'Denied by active higher-priority control'), ('superseded_by_later_command', 'Superseded by later command'), ('overridden_by_owner_admin', 'Overridden by owner/admin'), ('device_sync_reported', 'Device sync reported')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='activebulboverride',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('schedule', 'Schedule'), ('device', 'Device'), ('device-sync', 'Device Sync'), ('system', 'System')], default='manual', max_length=16),
        ),
        migrations.AlterField(
            model_name='controlactivity',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('schedule', 'Schedule'), ('device', 'Device'), ('device-sync', 'Device Sync'), ('system', 'System')], default='manual', max_length=16),
        ),
        migrations.CreateModel(
            name='ConflictEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('permission', 'Permission'), ('manual_vs_manual', 'Manual vs Manual'), ('manual_vs_schedule', 'Manual vs Schedule'), ('schedule_vs_schedule', 'Schedule vs Schedule')], max_length=32)),
                ('reason_code', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('permission_denied', 'Denied by permissions'), ('active_higher_priority_control', 'Denied by active higher-priority control'), ('superseded_by_later_command', 'Superseded by later command'), ('overridden_by_owner_admin', 'Overridden by owner/admin'), ('device_sync_reported', 'Device sync reported')], default='', max_length=64)),
                ('winner_summary', models.CharField(blank=True, default='', max_length=255)),
                ('loser_summary', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('bulb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_events', to='bulb.bulb')),
                ('losing_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_conflict_events', to='bulb.controlactivity')),
                ('winning_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_conflict_events', to='bulb.controlactivity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
