# Generated by Django 5.0.8 on 2026-02-07 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulb', '0005_lightschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lightschedule',
            old_name='set_on_state',
            new_name='target_is_on',
        ),
    ]
