# Generated by Django 5.0.8 on 2026-02-08 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulb', '0006_rename_set_on_state_lightschedule_target_is_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lightschedule',
            options={'ordering': ['run_at']},
        ),
    ]
