# Generated by Django 5.0.8 on 2026-02-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulb', '0007_alter_lightschedule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightschedule',
            name='claimed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
