# Generated by Django 5.0.8 on 2026-03-16 01:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulb', '0008_lightschedule_claimed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lightschedule',
            options={'ordering': ['next_run_at', 'id']},
        ),
        migrations.RenameField(
            model_name='lightschedule',
            old_name='executed_at',
            new_name='last_run_at',
        ),
        migrations.RemoveField(
            model_name='lightschedule',
            name='run_at',
        ),
        migrations.AddField(
            model_name='lightschedule',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lightschedule',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lightschedule',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lightschedule',
            name='next_run_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lightschedule',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lightschedule',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lightschedule',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lightschedule',
            name='time_of_day',
            field=models.TimeField(default=datetime.time(18, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lightschedule',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lightschedule',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
    ]
