# Generated by Django 5.0.8 on 2026-03-14 14:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulb', '0008_lightschedule_claimed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('current_rms', models.FloatField(help_text='Measured RMS current in amps')),
                ('estimated_voltage', models.FloatField(default=120, help_text='estimated voltage of the mains')),
                ('estimated_power_w', models.FloatField()),
                ('cumulative_energy_wh', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='lightschedule',
            name='run_at',
            field=models.DateTimeField(db_index=True, unique=True),
        ),
    ]
