# Generated by Django 5.0.8 on 2026-03-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulb', '0009_alter_lightschedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightschedule',
            name='timezone_name',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
