# Generated by Django 5.0.8 on 2026-03-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulb', '0009_powerreading_alter_lightschedule_run_at'),
        ('bulb', '0010_lightschedule_timezone_name'),
    ]

    operations = [
    ]
