services:
  dev:
    build:
      context: ../server
    env_file:
      - ../ops/env/.env
    volumes:
      - ../server:/app
      - ..:/workspace
    command: sleep infinity
    depends_on:
      - db
    ports:
          - "8000:8000"   # host:container (Django)


  db:
    image: postgres:16
    environment:
      POSTGRES_DB: smartlight
      POSTGRES_USER: smartlight
      POSTGRES_PASSWORD: smartlight
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata:
